### ISSUE TITLE
Не работают ctrl хот клавишы

### ISSUE THREAD

**Issue by Piligrimm27rus** [ets777/textarea#6]
Хачу скапировать а не выходит(9((
хачу вставить а не выходит(9((

Розработчик, прафикси пожалуста....

ps. ctrl стрелачки влева вправа не роботают(

**Comment by ets777** [comment]
> Хачу скапировать а не выходит(9((
> хачу вставить а не выходит(9((

пофикшено в версии 1.0.1

>ps. ctrl стрелачки влева вправа не роботают(

будет исправлено в 1.0.2
